Code Base/objects/AssembliedBOM__c.object
<CustomObject>
    <fields>
        <fullName>BOM__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>BOM</label>
        <referenceTo>BOM__c</referenceTo>
        <relationshipLabel>Assemblied BOMs</relationshipLabel>
        <relationshipName>Assemblied_BOMs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubAssemblyPrice__c</fullName>
        <formula>SUBQuantity__c *  BOM__r.UnitPrice__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub Assembly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubAssembly__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub Assembly</label>
        <referenceTo>SubAssembly__c</referenceTo>
        <relationshipLabel>Assemblied BOMs</relationshipLabel>
        <relationshipName>Assemblied_BOMs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Assemblied BOM</label>
    <nameField>
        <label>Assemblied BOM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assemblied BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/objects/BOM__c.object
<CustomObject>
    <fields>
        <fullName>BomPrice__c</fullName>
        <formula>QuantityUnit__c * UnitPrice__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Bom Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ProductID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finished ProductID</label>
        <referenceTo>Materials__c</referenceTo>
        <relationshipLabel>BOM</relationshipLabel>
        <relationshipName>BOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BOM</label>
    <nameField>
        <displayFormat>PART-{000000}</displayFormat>
        <label>BOM ID No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BOM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/objects/Materials__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Material</label>
    <nameField>
        <displayFormat>RMG-PROD{0000}</displayFormat>
        <label>ProductID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/objects/SubAssembly__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sub Assembly</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Assembly</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/objects/SubAssemblyBOM__c.object
<CustomObject>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material</label>
        <referenceTo>Materials__c</referenceTo>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubAssemblyBOMPrice__c</fullName>
        <formula>Sub_Assembly__r.Price__c *  Sub_Assembly_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PRICE</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Sub_Assembly__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sub Assembly</label>
        <referenceTo>SubAssembly__c</referenceTo>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>SubAssembly BOM</label>
    <nameField>
        <label>SubAssembly BOM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubAssembly BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/classes/MaterialService.cls
public  class MaterialService {   
    
    /**
    * Method to update the material price when a new bom is getting inserted.
    * 
    * */
    public  static void updateMaterialPriceOnInsert(List<BOM__c> newBom) {      
        
        Map<Id,Decimal> materialPriceMap= new Map<Id,Decimal>();
        for(Bom__c bom : newBom) {
            Decimal price= 0.0;
            if(materialPriceMap.get(bom.ProductID__c) != null) {
                price+= materialPriceMap.get(bom.ProductID__c);
                
            }
            
            if(bom.BomPrice__c != null) {
                price+= bom.BomPrice__c;
            }
            materialPriceMap.put(bom.ProductID__c,price);
        }
        List<Materials__c> materialList = [SELECT  Id,Price__c from Materials__c WHERE id = :materialPriceMap.keySet()];
        
        for (Materials__c material : materialList) {
            if(material.Price__c != null){
                material.Price__c += materialPriceMap.get(material.Id);
            } 
        }
        update materialList; 
    } 
    
    /**
    * Method to update the material price when bom is getting updated.
    * 
    * */ 
    public static void updateMaterialPriceOnUpdate(List<BOM__c> oldBom,List<BOM__c> newBom) {   
        
        List<AssembliedBOM__c> assembledBOMIds= [Select id,BOM__c,SubAssembly__c from AssembliedBOM__c where BOM__c in :newBom];
        Set<ID> materialIDs= new Set<ID>();
        Set<ID> subAssemblyIDs= new Set<ID>();
        for(AssembliedBOM__c assBom : assembledBOMIds) {
            if(assBom.SubAssembly__c != null) {
            	subAssemblyIDs.add(assBom.SubAssembly__c);   
            }
        }
        
        for(BOM__c bom : newBom) {
            if(bom.ProductID__c != null) {
            	materialIDs.add(bom.ProductID__c);   
            }
        }
        UpdatePriceInSubAssembly(subAssemblyIDs);
        UpdatePriceInMaterials(materialIDs);
        
        /*Map<Id,Decimal> newMaterialPriceMap= new Map<Id,Decimal>();
        Map<Id,Decimal> oldMaterialPriceMap= new Map<Id,Decimal>();
        for(Bom__c bom : newBom) {
            Decimal price= 0.0;
            if(newMaterialPriceMap.get(bom.ProductID__c) != null) {
                price+= newMaterialPriceMap.get(bom.ProductID__c);
            }
            if(bom.BomPrice__c != null) {
                price+= bom.BomPrice__c;
            }
            newMaterialPriceMap.put(bom.ProductID__c,price);
        }
        
        for(Bom__c bom : oldBom) {
            Decimal price= 0.0;
            if(oldMaterialPriceMap.get(bom.ProductID__c) != null) {
                price+= oldMaterialPriceMap.get(bom.ProductID__c);
            }
            if(bom.BomPrice__c != null) {
                price+= bom.BomPrice__c;
            }
            oldMaterialPriceMap.put(bom.ProductID__c,price);
        }
        List<Materials__c> materialList = [SELECT  Id,Price__c from Materials__c WHERE id = :newMaterialPriceMap.keySet()];
        for (Materials__c material : materialList) {
                if(material.Price__c == null) {
                    material.Price__c = 0;
                }
                if(material.Price__c == 0 || material.Price__c == 0.0) {
                    material.Price__c += newMaterialPriceMap.get(material.Id);        
                }
                else {
                    material.Price__c -= oldMaterialPriceMap.get(material.Id);
                	material.Price__c += newMaterialPriceMap.get(material.Id);        
                }
            //material.Price__c += newMaterialPriceMap.get(material.Id);        
        }
        update materialList;   
        List<AssembliedBOM__c> assembledBOMs= [Select id,BOM__c from AssembliedBOM__c where BOM__c in :newBom];
        update assembledBOMs;
		*/
    }
    
    /**
    * Method to update the material price when bom is getting deleted.
    * 
    * */
    public static void UpdateMaterialPriceOnDelete(List<BOM__c> delBom) {
        
        Map<Id,Decimal> materialPriceMap= new Map<Id,Decimal>();
        for(Bom__c bom : delBom) {
            Decimal price= 0.0;
            if(materialPriceMap.get(bom.ProductID__c) != null) {
                price+= materialPriceMap.get(bom.ProductID__c);
            }
            if(bom.BomPrice__c != null) {
                price+= bom.BomPrice__c;
            }
            materialPriceMap.put(bom.ProductID__c,price);
        }
        
        List<Materials__c> materialList = [SELECT  Id,Price__c from Materials__c WHERE id = :materialPriceMap.keySet()];
        
        for (Materials__c material : materialList) {
            if(material.Price__c != null && (material.Price__c != 0 || material.Price__c != 0.0)){
                material.Price__c -= materialPriceMap.get(material.Id);
            }
        }
        update materialList; 
    }
    
    public static void UpdatePriceInSubAssembly(Set<ID> subAssemblyIDs) {
        
        List<SubAssembly__c> subAssemblyList= [Select id,Price__c,(select id,SubAssemblyPrice__c from Assemblied_BOMs__r) from SubAssembly__c where id in :subAssemblyIDs];
        for(SubAssembly__c subAssembly : subAssemblyList) {
            List<AssembliedBOM__c> assembledBOMs= subAssembly.Assemblied_BOMs__r;
            decimal subAssemblyPrice= 0.0;
            for(AssembliedBOM__c record : assembledBOMs) {
                subAssemblyPrice+= record.SubAssemblyPrice__c;
            }
            subAssembly.Price__c= subAssemblyPrice;
        }
        update subAssemblyList;
    }
    
    public static void UpdatePriceInMaterials(Set<ID> materialIDs) {
        
        List<Materials__c> materialList= [Select id,Price__c,(select id,BomPrice__c from BOM__r),
                                          (Select id,SubAssemblyBOMPrice__c from Components__r) from Materials__c where id in :materialIDs];
        for(Materials__c material : materialList) {
            List<BOM__c> boms= material.BOM__r;
            List<SubAssemblyBOM__c> subAssemblies= material.Components__r;
            decimal bomPrice= 0.0;
            decimal subAssemblyPrice= 0.0;
            for(BOM__c record : boms) {
                bomPrice+= record.BomPrice__c;
            }
            for(SubAssemblyBOM__c record : subAssemblies) {
                subAssemblyPrice+= record.SubAssemblyBOMPrice__c;
            }
            material.Price__c= bomPrice + subAssemblyPrice;
        }
        update materialList;
    }
        
}