Code Base/objects/AssembliedBOM__c.object
<CustomObject>
    <fields>
        <fullName>SubAssemblyPrice__c</fullName>
        <formula>SUBQuantity__c *  BOM__r.UnitPrice__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Sub Assembly Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>SubAssembly__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub Assembly</label>
        <referenceTo>SubAssembly__c</referenceTo>
        <relationshipLabel>Assemblied BOMs</relationshipLabel>
        <relationshipName>Assemblied_BOMs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Assemblied BOM</label>
    <nameField>
        <label>Assemblied BOM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assemblied BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/objects/SubAssembly__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sub Assembly</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Assembly</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/classes/AssembliedBOMService.cls
public class AssembliedBOMService {
    
    /**
    * Method to update the material price when a new SubAssemblyBom is getting inserted.
    * 
    * */
    public  static void updateSubAssemblyPriceOnInsert(List<AssembliedBOM__c> assembliedBOMList) {
        
        Map<Id,Decimal> subAssemblyPriceMap = new Map<Id,Decimal>();
        
        for(AssembliedBOM__c assembliedBOM : assembliedBOMList) {
            Decimal price= 0.0;
            if(subAssemblyPriceMap.get(assembliedBOM.SubAssembly__c) != null) {
                price+= subAssemblyPriceMap.get(assembliedBOM.SubAssembly__c);
            }
            if(assembliedBOM.SubAssemblyPrice__c != null) {
                price+= assembliedBOM.SubAssemblyPrice__c;
            }
            subAssemblyPriceMap.put(assembliedBOM.SubAssembly__c,price);
        }
        
        List<SubAssembly__c> subAssemblyList= [Select id,Price__c from SubAssembly__c where id in :subAssemblyPriceMap.keyset()];
        
        for(SubAssembly__c subAssembly : subAssemblyList) {
            subAssembly.Price__c+= subAssemblyPriceMap.get(subAssembly.Id);
        }
        update subAssemblyList;
    }
    
    /**
    * Method to update the material price when SubAssemblyBom is getting updated.
    * 
    * */ 
    public static void updateSubAssemblyPriceOnUpdate(List<AssembliedBOM__c> oldAssembliedBOMList,List<AssembliedBOM__c> newAssembliedBOMList) {
        
        Map<Id,Decimal> newMaterialPriceMap= new Map<Id,Decimal>();
        Map<Id,Decimal> oldMaterialPriceMap= new Map<Id,Decimal>();
        
        for(AssembliedBOM__c bom : newAssembliedBOMList) {
            Decimal price= 0.0;
            if(newMaterialPriceMap.get(bom.SubAssembly__c) != null) {
                price+= newMaterialPriceMap.get(bom.SubAssembly__c);
            }
            if(bom.SubAssemblyPrice__c != null) {
                price+= bom.SubAssemblyPrice__c;
            }
            system.debug('new: '+price);
            newMaterialPriceMap.put(bom.SubAssembly__c,price);
        }
        
        for(AssembliedBOM__c bom : oldAssembliedBOMList) {
            Decimal price= 0.0;
            if(oldMaterialPriceMap.get(bom.SubAssembly__c) != null) {
                price+= oldMaterialPriceMap.get(bom.SubAssembly__c);
            }
            if(bom.SubAssemblyPrice__c != null) {
                price+= bom.SubAssemblyPrice__c;
            }
            system.debug('old: '+price);
            oldMaterialPriceMap.put(bom.SubAssembly__c,price);
        }
        
        List<SubAssembly__c> subAssemblyList= [Select id,Price__c from SubAssembly__c where id in :newMaterialPriceMap.keyset()];
        system.debug('subAssemblyList: '+subAssemblyList);
        for (SubAssembly__c subAssembly : subAssemblyList) {
                if(subAssembly.Price__c == null) {
                    subAssembly.Price__c = 0;
                }
                if(subAssembly.Price__c == 0 || subAssembly.Price__c == 0.0) {
                	subAssembly.Price__c += newMaterialPriceMap.get(subAssembly.Id);
                }
                else {
                	subAssembly.Price__c -= oldMaterialPriceMap.get(subAssembly.Id);
                	subAssembly.Price__c += newMaterialPriceMap.get(subAssembly.Id);    
                }
            //subAssembly.Price__c += newMaterialPriceMap.get(subAssembly.Id);
        }
        update subAssemblyList; 
    }
    
    /**
    * Method to update the material price when SubAssemblyBom is getting deleted.
    * 
    * */
    public static void UpdateSubAssemblyPriceOnDelete(List<AssembliedBOM__c> delAssemblyBom) {
        
        Map<Id,Decimal> materialPriceMap= new Map<Id,Decimal>();
        for(AssembliedBOM__c bom : delAssemblyBom) {
            Decimal price= 0.0;
            if(materialPriceMap.get(bom.SubAssembly__c) != null) {
                price+= materialPriceMap.get(bom.SubAssembly__c);
            }
            if(bom.SubAssemblyPrice__c != null) {
                price+= bom.SubAssemblyPrice__c;
            }
            materialPriceMap.put(bom.SubAssembly__c,price);
        }
        
        List<SubAssembly__c> subAssemblyList= [Select id,Price__c from SubAssembly__c where id in :materialPriceMap.keySet()];
        
        for (SubAssembly__c subAssembly : subAssemblyList) {
            if(subAssembly.Price__c != null && (subAssembly.Price__c != 0 || subAssembly.Price__c != 0.0)){
                subAssembly.Price__c -= materialPriceMap.get(subAssembly.Id);
            } 
        }
        update subAssemblyList;  
    }    
}