Code Base/objects/AssembliedBOM__c.object
<CustomObject>
    <fields>
        <fullName>BOM__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>BOM</label>
        <referenceTo>BOM__c</referenceTo>
        <relationshipLabel>Assemblied BOMs</relationshipLabel>
        <relationshipName>Assemblied_BOMs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SUBQuantity__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SubAssembly__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Sub Assembly</label>
        <referenceTo>SubAssembly__c</referenceTo>
        <relationshipLabel>Assemblied BOMs</relationshipLabel>
        <relationshipName>Assemblied_BOMs</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Assemblied BOM</label>
    <nameField>
        <label>Assemblied BOM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assemblied BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/objects/BOM__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Electronic Item~E</fullName>
                </value>
                <value>
                    <fullName>Mechanical Item~M</fullName>
                </value>
                <value>
                    <fullName>Consumables~C</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous~MS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finished ProductID</label>
        <referenceTo>Materials__c</referenceTo>
        <relationshipLabel>BOM</relationshipLabel>
        <relationshipName>BOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuantityUnit__c</fullName>
        <defaultValue>1</defaultValue>
        <label>General Quantity</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <label>BOM</label>
    <nameField>
        <displayFormat>PART-{000000}</displayFormat>
        <label>BOM ID No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BOM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/objects/ConfigMaterial__c.object
<CustomObject>
    <description>This object is created for configuring sub-category with its param for materials.</description>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Electronic Item~E</fullName>
                </value>
                <value>
                    <fullName>Mechanical Item~M</fullName>
                </value>
                <value>
                    <fullName>Consumables~C</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous~MS</fullName>
                </value>
                <value>
                    <fullName>Sub Assembly~SA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ParamName1__c</fullName>
        <label>ParamName1</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubCategory__c</fullName>
        <label>SubCategory</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>ConfigMaterial</label>
    <nameField>
        <displayFormat>config-{000}</displayFormat>
        <label>ConfigMaterial Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ConfigMaterials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/objects/Materials__c.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RMG_Product_Code__c</fullName>
        <label>RMG Product Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Material</label>
    <nameField>
        <displayFormat>RMG-PROD{0000}</displayFormat>
        <label>ProductID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/objects/Part_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Electronic Item~E</fullName>
                </value>
                <value>
                    <fullName>Mechanical Item~M</fullName>
                </value>
                <value>
                    <fullName>Consumables~C</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous~MS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Part Detail</label>
    <nameField>
        <displayFormat>SPECS-{00000}</displayFormat>
        <label>Part Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/objects/SubAssembly__c.object
<CustomObject>
    <fields>
        <fullName>SubAssemblyID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>SubAssembly ID</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Sub Assembly</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Assembly</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/classes/MaterialsRelatedListControllerTest.cls
@isTest
public class MaterialsRelatedListControllerTest {
    
    @testSetup
    static void setup() {
        
        List<Materials__c> materialList = new List<Materials__c>();
        Materials__c material = new Materials__c(RMG_Product_Code__c='Material1',Product_Type__c='Position Transmitter');
        materialList.add(material);
        insert materialList;
        
        List<Bom__c> bomList = new List<Bom__c>();
        Bom__c bom1 = new Bom__c(QuantityUnit__c=10,ProductID__c=materialList[0].id,Category__c='Electronic Item~E');
        Bom__c bom2 = new Bom__c(QuantityUnit__c=20,ProductID__c=materialList[0].id,Category__c='Electronic Item~E');
        bomList.add(bom1);
        bomList.add(bom2);
        
        insert bomList;    
        
        configMaterial__c configMaterial = new configMaterial__c(subcategory__c='Wire~WR',ParamName1__c='WR Type'); 
        insert configMaterial;
        
        //List<SubAssembly__c> subAssemblyList= new List<SubAssembly__c>();
        SubAssembly__c subAssembly= new SubAssembly__c(SubAssemblyID__c='Test subAssembly',Name='SubAssembly1');
        insert subAssembly;
        
        AssembliedBOM__c assembledBOM= new AssembliedBOM__c(BOM__c=bomList.get(0).Id,SubAssembly__c=subAssembly.Id,SUBQuantity__c=5);
        insert assembledBOM;
        
    }
    
    public static testmethod void testFetchBOMInSubAssembly(){
        Test.startTest();
        SubAssembly__c subAssembly = [Select id from SubAssembly__c where Name='SubAssembly1' Limit 1];
        List<object> result = MaterialsRelatedListController.fetchBOMInSubAssembly(subAssembly.Id);
        system.debug('result: '+ result);
        system.assert(result.size() > 0, 'No material found');
        Test.stopTest();
    }
    
    public static testmethod void testFetchBOMDetails(){
        Test.startTest();
        Materials__c material = [Select id from Materials__c where RMG_Product_Code__c='Material1' Limit 1];
        List<object> result = MaterialsRelatedListController.fetchBOMDetails(material.id);
        system.debug('result: '+ result);
        system.assert(result.size() > 0, 'No material found');
        Test.stopTest();
    }
    
    public static testmethod void testSavePartDetail() {
        Test.startTest();
        Part_Detail__c pd = new Part_Detail__c(Category__c='Electronic Item~E');
        Part_Detail__c result = MaterialsRelatedListController.savePartDetail(pd);
        system.assert(result != null,'part detail not inserted');
        Test.stopTest();
    }
    
    public static testmethod void testSaveBOM() {
        Test.startTest();
        BOM__c pd = new BOM__c(Category__c='Electronic Item~E');
        BOM__c result = MaterialsRelatedListController.saveBOM(pd);
        system.assert(result != null,'BOM not inserted');
        Test.stopTest();
    }
    
    public static testmethod void testFetchParams() {
        Test.startTest();
        List<configMaterial__c> configMaterialRecords = [select id,subCategory__c from configMaterial__c limit 1];
        List<String> result = MaterialsRelatedListController.fetchParams(configMaterialRecords.get(0).subCategory__c);
        system.assert(result.size() > 0,'No records configured in configMaterial object');
        Test.stopTest();
    }
}