Code Base/objects/BOM__c.object
<CustomObject>
    <fields>
        <fullName>MakeSupplier__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Make/Supplier</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>BOM</relationshipLabel>
        <relationshipName>BOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MaterialPartName__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Material and Part Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Part_Detail_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Detail ID</label>
        <referenceTo>Part_Detail__c</referenceTo>
        <relationshipLabel>BOM</relationshipLabel>
        <relationshipName>BOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finished ProductID</label>
        <referenceTo>Materials__c</referenceTo>
        <relationshipLabel>BOM</relationshipLabel>
        <relationshipName>BOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>BOM</label>
    <nameField>
        <displayFormat>PART-{000000}</displayFormat>
        <label>BOM ID No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BOM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/classes/BomInsertService.cls
public class BomInsertService {
    
    
    /**check bom duplicate before inserting a bom record **/
    
    public  static void preventDuplicateBomOnInsert(List<BOM__c> newBom) {   
        for(BOM__c bom : newBom) {
            if(bom.ProductID__c !=null && bom.Part_Detail_ID__c != null && bom.MakeSupplier__c  != null) {
                bom.MaterialPartName__c=  bom.MakeSupplier__c + '-'  +  bom.Part_Detail_ID__c  + '-' + bom.ProductID__c;
            } 
        }   
    }
    
    /**check bom duplicate before updating a bom record **/
    public static void preventDuplicateBomOnUpdate(List<BOM__c> newBom) {
        
        for (BOM__c bom: newBom) {
 			//if(bom.ProductID__c !=null && bom.Part_Detail_ID__c != null && bom.MakeSupplier__c  != null) {
               bom.MaterialPartName__c    =  bom.MakeSupplier__c + '-'  +  bom.Part_Detail_ID__c + '-' + bom.ProductID__c;
            //} 
        }      
    }
}