Code Base/objects/BOM__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Electronic Item~E</fullName>
                </value>
                <value>
                    <fullName>Mechanical Item~M</fullName>
                </value>
                <value>
                    <fullName>Consumables~C</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous~MS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MeasurementUnit__c</fullName>
        <formula>TEXT(Part_Detail_ID__r.MeasurementUnit__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Measurement Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Part_Detail_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Part Detail ID</label>
        <referenceTo>Part_Detail__c</referenceTo>
        <relationshipLabel>BOM</relationshipLabel>
        <relationshipName>BOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Finished ProductID</label>
        <referenceTo>Materials__c</referenceTo>
        <relationshipLabel>BOM</relationshipLabel>
        <relationshipName>BOM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuantityUnit__c</fullName>
        <defaultValue>1</defaultValue>
        <label>General Quantity</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <formula>Text(Part_Detail_ID__r.Sub_Category__c)</formula>
        <label>Sub-Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Enter the amount of a single part</description>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>BOM</label>
    <nameField>
        <displayFormat>PART-{000000}</displayFormat>
        <label>BOM ID No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BOM</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/objects/Materials__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RMG_Product_Code__c</fullName>
        <label>RMG Product Code</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Material</label>
    <nameField>
        <displayFormat>RMG-PROD{0000}</displayFormat>
        <label>ProductID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/objects/Part_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Electronic Item~E</fullName>
                </value>
                <value>
                    <fullName>Mechanical Item~M</fullName>
                </value>
                <value>
                    <fullName>Consumables~C</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous~MS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MeasurementUnit__c</fullName>
        <label>Measurement Unit</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>nos</fullName>
                </value>
                <value>
                    <fullName>mm</fullName>
                </value>
                <value>
                    <fullName>gms</fullName>
                </value>
                <value>
                    <fullName>ltr</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Parameter_Value_1__c</fullName>
        <label>Parameter Value 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parameter_Value_2__c</fullName>
        <label>Parameter Value 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub-Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Base~BSE</fullName>
                </value>
                <value>
                    <fullName>Book~BOOK</fullName>
                </value>
                <value>
                    <fullName>Capacitor~CC</fullName>
                </value>
                <value>
                    <fullName>Cleaning Agent~CLA</fullName>
                </value>
                <value>
                    <fullName>Component~CPT</fullName>
                </value>
                <value>
                    <fullName>Conformal Coating~CMCT</fullName>
                </value>
                <value>
                    <fullName>Connector~CN</fullName>
                </value>
                <value>
                    <fullName>Core~CRE</fullName>
                </value>
                <value>
                    <fullName>Cover~CVR</fullName>
                </value>
                <value>
                    <fullName>Diode~DI</fullName>
                </value>
                <value>
                    <fullName>Encapsulation / Adhesives~ECP</fullName>
                </value>
                <value>
                    <fullName>Fastener~FSR</fullName>
                </value>
                <value>
                    <fullName>Integrated Chip~IC</fullName>
                </value>
                <value>
                    <fullName>O-Ring~OR</fullName>
                </value>
                <value>
                    <fullName>Packing Box~PBX</fullName>
                </value>
                <value>
                    <fullName>Packing Materials~PCK</fullName>
                </value>
                <value>
                    <fullName>Plate~PLT</fullName>
                </value>
                <value>
                    <fullName>Potting Materials~PTMLS</fullName>
                </value>
                <value>
                    <fullName>Printed Circuit Board~PC</fullName>
                </value>
                <value>
                    <fullName>Resistor~RE</fullName>
                </value>
                <value>
                    <fullName>Sheet~ST</fullName>
                </value>
                <value>
                    <fullName>Sleeve~SLV</fullName>
                </value>
                <value>
                    <fullName>Solder~SDR</fullName>
                </value>
                <value>
                    <fullName>Solder Flux~FLX</fullName>
                </value>
                <value>
                    <fullName>Sticker~STK</fullName>
                </value>
                <value>
                    <fullName>Switch~SW</fullName>
                </value>
                <value>
                    <fullName>Tape~TPE</fullName>
                </value>
                <value>
                    <fullName>Transipad~TSP</fullName>
                </value>
                <value>
                    <fullName>Transistor~TR</fullName>
                </value>
                <value>
                    <fullName>Trimpot~TP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Part Detail</label>
    <nameField>
        <displayFormat>SPECS-{00000}</displayFormat>
        <label>Part Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/classes/BomTriggerHandlerTest.cls
@isTest
public class BomTriggerHandlerTest {
    @testSetup
    static void setup() {
        List<Materials__c> materialList = new List<Materials__c>();        
        for (integer i = 1;i  <5;i++) {
            materialList.add(new Materials__c(RMG_Product_Code__c='TestMaterial'+i,Product_Type__c='Position Transmitter'));
        }
        insert materialList;

        Part_Detail__c partDetailTest = new Part_Detail__c(Category__c='Consumables~C',MeasurementUnit__c = 'nos',Sub_Category__c= ' '	,Parameter_Value_1__c  ='Test~t'	,Parameter_Value_2__c = 'Test2~t2');
        
     /*   List <Account> AccountList= new List<Account>();
        for (integer i= 1;i<2;i++) {
            Account Testaccount = new Account(Name = 'TestAccount' + i,RecordTypeId = '0120T0000000LiXQAU');
                
                }*/
        
        
        List<BOM__c> bomList = new List<BOM__c>();    
        BOM__c bom1 = new BOM__c(UnitPrice__c= 20,QuantityUnit__c= 2,ProductID__c=materialList[0].id );
        BOM__c bom2 = new BOM__c(UnitPrice__c= 20,QuantityUnit__c= 2,ProductID__c=materialList[1].id );
        BOM__c bom3 = new BOM__c(UnitPrice__c= 20,QuantityUnit__c= 2,ProductID__c=materialList[2].id );
        BOM__c bom4 = new BOM__c(UnitPrice__c= 0,QuantityUnit__c= 2,ProductID__c=materialList[0].id );
        
        //test data for unique id change.
        BOM__c bom5 = new BOM__c(ProductID__c=materialList[3].id,Part_Detail_ID__c	= partDetailTest.id);
        
        bomList.add(bom1);
        bomList.add(bom2);
        bomList.add(bom3);
        bomList.add(bom4);
        bomList.add(bom5);
        
        
        insert bomList; 
        
    
        
        
        BOM__c bom2update = [Select id,UnitPrice__c,QuantityUnit__c from BOM__C where ProductID__c= :materialList[1].id];
        bom2update.UnitPrice__c  = 50;
        bom2update.QuantityUnit__c = 3;
        update bom2update;
        
        BOM__c bom3delete = [Select id from BOM__c where ProductID__c= :materialList[2].id];
        delete bom3delete;
        
        
        BOM__c bom6 = new BOM__c(ProductID__c=materialList[3].id,Part_Detail_ID__c	= partDetailTest.id);
        
        insert bom6;
        
    }
    
    public testmethod static void testOnAfterInsert() {
        
        Test.startTest();
        Materials__c TestMaterial1   = [Select id,Price__c from Materials__c where RMG_Product_Code__c='TestMaterial1'];
        System.assertEquals(TestMaterial1.Price__c,40);
        Test.stopTest();
        
    }
    
    public testmethod static void testOnAfterUpdate() {
        Test.startTest();
        Materials__c TestMaterial2   = [Select id,Price__c from Materials__c where RMG_Product_Code__c='TestMaterial2'];
        System.assertEquals(TestMaterial2.Price__c,150);
        Test.stopTest();
        
    }
    
    public testmethod static void testOnAfterDelete()  {
        Test.startTest();
        Materials__c TestMaterial3   = [Select id,Price__c from Materials__c where RMG_Product_Code__c='TestMaterial3'];
        System.assertEquals(TestMaterial3.Price__c,0);
        Test.stopTest();
    }
    
   /* public testmethod static void testonBeforeDelete() {
        Test.startTest();
    }        */

}