Code Base/objects/Materials__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Material</label>
    <nameField>
        <displayFormat>RMG-PROD{0000}</displayFormat>
        <label>ProductID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Materials</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/objects/SubAssemblyBOM__c.object
<CustomObject>
    <fields>
        <fullName>Material__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Material</label>
        <referenceTo>Materials__c</referenceTo>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubAssemblyBOMPrice__c</fullName>
        <formula>Sub_Assembly__r.Price__c *  Sub_Assembly_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PRICE</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>SubAssembly BOM</label>
    <nameField>
        <label>SubAssembly BOM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SubAssembly BOMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/classes/SubAssemblyBOMService.cls
public class SubAssemblyBOMService {
    
     /**
     * Method to update the material price when a new SubAssemblyBom is getting inserted.
     * 
     * */
    public  static void updateMaterialPriceOnInsert(List<SubAssemblyBOM__c> newSubAssemblyBom) {
        
        Map<Id,Decimal> materialPriceMap= new Map<Id,Decimal>();
        
        for(SubAssemblyBOM__c bom : newSubAssemblyBom) {
            Decimal price= 0.0;
            if(materialPriceMap.get(bom.Material__c) != null) {
                price+= materialPriceMap.get(bom.Material__c);
            }
            if(bom.SubAssemblyBOMPrice__c != null) {
                price+= bom.SubAssemblyBOMPrice__c;
            }
            materialPriceMap.put(bom.Material__c,price);
        }
        List<Materials__c> materialList = [SELECT  Id,Price__c from Materials__c WHERE id = :materialPriceMap.keySet()];
        
        for (Materials__c material : materialList) {
            if(material.Price__c != null){
                material.Price__c += materialPriceMap.get(material.Id);
            } 
        }
        update materialList; 
        
    }
    
    /**
     * Method to update the material price when SubAssemblyBom is getting updated.
     * 
     * */ 
    public static void updateMaterialPriceOnUpdate(List<SubAssemblyBOM__c> oldSubAssemblyBom,List<SubAssemblyBOM__c> newSubAssemblyBom) {
        
        Map<Id,Decimal> newMaterialPriceMap= new Map<Id,Decimal>();
        Map<Id,Decimal> oldMaterialPriceMap= new Map<Id,Decimal>();
        
        for(SubAssemblyBOM__c bom : newSubAssemblyBom) {
            Decimal price= 0.0;
            if(newMaterialPriceMap.get(bom.Material__c) != null) {
                price+= newMaterialPriceMap.get(bom.Material__c);
            }
            if(bom.SubAssemblyBOMPrice__c != null) {
                price+= bom.SubAssemblyBOMPrice__c;
            }
            newMaterialPriceMap.put(bom.Material__c,price);
        }
        
        for(SubAssemblyBOM__c bom : oldSubAssemblyBom) {
            Decimal price= 0.0;
            if(oldMaterialPriceMap.get(bom.Material__c) != null) {
                price+= oldMaterialPriceMap.get(bom.Material__c);
            }
            if(bom.SubAssemblyBOMPrice__c != null) {
                price+= bom.SubAssemblyBOMPrice__c;
            }
            oldMaterialPriceMap.put(bom.Material__c,price);
        }
        
        List<Materials__c> materialList = [SELECT  Id,Price__c from Materials__c WHERE id = :newMaterialPriceMap.keySet()];
        
        for (Materials__c material : materialList) {
                if(material.Price__c == null ) {
                    material.Price__c = 0;
                }
                if(material.Price__c == 0 || material.Price__c == 0.0) {
                    material.Price__c += newMaterialPriceMap.get(material.Id);
                }
                else {
            		material.Price__c -= oldMaterialPriceMap.get(material.Id);
                	material.Price__c += newMaterialPriceMap.get(material.Id);        
                }
            //material.Price__c += newMaterialPriceMap.get(material.Id);
        }
        update materialList; 
    }
    
    /**
     * Method to update the material price when SubAssemblyBom is getting deleted.
     * 
     * */
    public static void UpdateMaterialPriceOnDelete(List<SubAssemblyBOM__c> delSubAssemblyBom) {
        
        Map<Id,Decimal> materialPriceMap= new Map<Id,Decimal>();
        for(SubAssemblyBOM__c bom : delSubAssemblyBom) {
            Decimal price= 0.0;
            if(materialPriceMap.get(bom.Material__c) != null) {
                price+= materialPriceMap.get(bom.Material__c);
            }
            if(bom.SubAssemblyBOMPrice__c != null) {
                price+= bom.SubAssemblyBOMPrice__c;
            }
            materialPriceMap.put(bom.Material__c,price);
        }
        
        List<Materials__c> materialList = [SELECT  Id,Price__c from Materials__c WHERE id = :materialPriceMap.keySet()];
        
        for (Materials__c material : materialList) {
            if(material.Price__c != null && (material.Price__c != 0 || material.Price__c != 0.0)){
                material.Price__c -= materialPriceMap.get(material.Id);
            } 
        }
        update materialList;  
    }    
}