Code Base/objects/Part_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Electronic Item~E</fullName>
                </value>
                <value>
                    <fullName>Mechanical Item~M</fullName>
                </value>
                <value>
                    <fullName>Consumables~C</fullName>
                </value>
                <value>
                    <fullName>Miscellaneous~MS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Part Detail</label>
    <nameField>
        <displayFormat>SPECS-{00000}</displayFormat>
        <label>Part Detail ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Part Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Code Base/classes/CustomLookupControllerTest.cls
@isTest
public class CustomLookupControllerTest {

     @testSetup
    static void setup() {
        Part_Detail__c pd = new Part_Detail__c(Category__c='Electronic Item~E');
        insert pd;
    }
    public static testmethod void testFetchRecordsWithoutValue() {
        Test.startTest();
        List<object> result = CustomLookupController.fetchRecords('Part_Detail__c','Category__c',null,'Item','');
        system.assert(result != null,'No result for the search');
        Test.stopTest();
    }
    
    public static testmethod void testFetchRecordsWithValue() {
        Test.startTest();
        Part_Detail__c pd = new Part_Detail__c(Category__c='Mechanical Item~M');
        insert pd;
        List<object> result = CustomLookupController.fetchRecords('Part_Detail__c','Category__c',null,'Mech',pd.Id);
        system.assert(result != null,'No result for the search');
        Test.stopTest();
    }
}